from typing import Protocol

from mosaic_api.domain import AuditEvent, Group, GroupMembership, Principal


class DirectoryRepository(Protocol):
    async def ready(self) -> bool: ...

    async def close(self) -> None: ...

    async def list_principals(self, tenant_id: str) -> list[Principal]: ...

    async def get_principal(self, tenant_id: str, principal_id: str) -> Principal | None: ...

    async def find_principal_by_object_id(
        self, tenant_id: str, object_id: str
    ) -> Principal | None: ...

    async def save_principal(self, principal: Principal, audit_event: AuditEvent) -> Principal: ...

    async def create_principal(
        self, principal: Principal, audit_event: AuditEvent
    ) -> Principal: ...

    async def delete_principal(self, principal: Principal, audit_event: AuditEvent) -> None: ...

    async def list_groups(self, tenant_id: str) -> list[Group]: ...

    async def get_group(self, tenant_id: str, group_id: str) -> Group | None: ...

    async def find_group_by_name(self, tenant_id: str, name: str) -> Group | None: ...

    async def save_group(self, group: Group, audit_event: AuditEvent) -> Group: ...

    async def create_group(self, group: Group, audit_event: AuditEvent) -> Group: ...

    async def delete_group(self, group: Group, audit_event: AuditEvent) -> None: ...

    async def list_memberships(
        self, tenant_id: str, *, group_id: str | None = None, principal_id: str | None = None
    ) -> list[GroupMembership]: ...

    async def get_membership(
        self, tenant_id: str, group_id: str, principal_id: str
    ) -> GroupMembership | None: ...

    async def create_membership(
        self,
        membership: GroupMembership,
        group: Group,
        principal: Principal,
        audit_event: AuditEvent,
    ) -> GroupMembership: ...

    async def delete_membership(
        self, membership: GroupMembership, audit_event: AuditEvent
    ) -> None: ...
