import { createHash } from 'node:crypto'
import { cents, type ModelJourneys, ModelProofError } from './model-config.ts'
import type { ModelObservation } from './model-runtime.ts'

export interface RuntimeEvidence {
  journey: string
  scopeSha256: string
  observations: ModelObservation[]
  timing?: {
    blockSave: { startedAt: string; savedAt: string }
    raiseSave: { startedAt: string; savedAt: string }
    first403At: string
    firstSuccessAt: string
  }
}
export interface IndependentModelEvidence {
  scopeSha256: string
  /** Human extracts independently captured rows; these are not generated by the runtime verifier. */
  attribution?: { source: 'logAnalytics'; requestId: string; grantId: string; costCenterId: string }[]
  backend?: { source: 'backend-capture'; requestId: string; headerNames: string[] }[]
  denials?: { source: 'gateway-trace'; requestId: string; message: string }[]
  namedValues?: {
    source: 'arm-get'
    phase: 'before' | 'block' | 'raise'
    gatewayId: string
    secret: boolean
    value: string
    observedAt: string
    writeAuditAt?: string
    auditAction?: string
  }[]
  government?: {
    cloud: string
    resourceDeployed: boolean
    domainDeployed: boolean
    managedIdentity: boolean
    tokenScope: string
    apiVersion: string
    attempts: { operationId: string; at: string; status: number }[]
    receipts: { operationId: string; messageId: string; receivedAt: string }[]
    mailboxObservation: EvidenceWindow
  }
}

export interface EvidenceWindow {
  startedAt: string
  completedAt: string
}

function timestamp(value: string | undefined): number {
  const n = value === undefined ? NaN : Date.parse(value)
  if (!Number.isFinite(n)) throw new ModelProofError('Missing measured evidence timestamp')
  return n
}

function observationWindow(window: EvidenceWindow, after: number): number {
  const start = timestamp(window?.startedAt)
  const end = timestamp(window?.completedAt)
  if (start < after || end <= start) throw new ModelProofError('Need a measured post-retry/recheck observation window')
  return end
}

function denial(evidence: IndependentModelEvidence, observation: ModelObservation, reason: string): void {
  const row = evidence.denials?.filter((d) => d.requestId === observation.requestId)
  if (!observation.requestId || row?.length !== 1 || row[0].source !== 'gateway-trace' ||
      !new RegExp(`^mosaic-deny v=1 r=${reason}(?: |$)`).test(row[0].message)) throw new ModelProofError(`Missing or incorrect independent denial trace for ${observation.case}`)
}

function one(runtime: RuntimeEvidence, label: string, status: number): ModelObservation {
  const matches = runtime.observations.filter((o) => o.case === label && o.status === status)
  if (matches.length !== 1 || !matches[0].requestId) throw new ModelProofError(`Missing uniquely correlated runtime case ${label}`)
  return matches[0]
}

export function selectionEvidence(scope: ModelJourneys, runtime: RuntimeEvidence, evidence: IndependentModelEvidence): void {
  for (const [label, grant] of [
    ['entra-default-explicit', scope.selection.default],
    ['entra-other-case-insensitive', scope.selection.other],
    ['entra-default-implicit', scope.selection.default],
    ['key-own-case-insensitive', scope.selection.default],
    ['key-implicit', scope.selection.default],
  ] as const) {
    const result = one(runtime, label, 200)
    const rows = evidence.attribution?.filter((a) => a.requestId === result.requestId)
    if (rows?.length !== 1 || rows[0].source !== 'logAnalytics' || rows[0].grantId !== grant.id ||
        rows[0].costCenterId !== grant.costCenterId) throw new ModelProofError(`Analytics did not attribute ${label} to the exact selected grant`)
    if (label !== 'entra-default-implicit' && label !== 'key-implicit') {
      const captures = evidence.backend?.filter((b) => b.requestId === result.requestId)
      if (captures?.length !== 1 || captures[0].source !== 'backend-capture' ||
          !Array.isArray(captures[0].headerNames) || captures[0].headerNames.length === 0 ||
          captures[0].headerNames.some((h) => h.toLowerCase() === 'x-mosaic-cost-center')) {
        throw new ModelProofError(`No independent on-wire header stripping proof for ${label}; XML is not a backend capture`)
      }
    }
  }
  denial(evidence, one(runtime, 'entra-unknown', 403), 'cost-center')
  denial(evidence, one(runtime, 'entra-malformed', 403), 'cost-center')
  denial(evidence, one(runtime, 'key-other', 403), 'cost-center-mismatch')
}

function blockedKeys(value: string): string[] {
  if (!/^(-|[0-9a-f]{12}(,[0-9a-f]{12})*)$/.test(value)) throw new ModelProofError('ARM named value is malformed')
  const keys = value === '-' ? [] : value.split(',')
  if (new Set(keys).size !== keys.length) throw new ModelProofError('ARM named value has duplicate keys')
  return keys.sort()
}

export function propagationEvidence(scope: ModelJourneys, runtime: RuntimeEvidence, evidence: IndependentModelEvidence) {
  if (!scope.budget || !runtime.timing) throw new ModelProofError('Missing budget scope or measured runtime timings')
  const timing = runtime.timing
  const probe = (phase: 'block' | 'raise', status: number, at: string) => {
    const matches = runtime.observations.filter((o) => o.grant === scope.budget!.grant.id && o.status === status &&
      new RegExp(`^budget-${phase}-probe-[1-9]\\d*$`).test(o.case))
    const firstAt = Math.min(...matches.map((o) => timestamp(o.at)))
    const first = matches.filter((o) => timestamp(o.at) === timestamp(at))
    if (first.length !== 1 || !first[0].requestId || timestamp(at) !== firstAt ||
        runtime.observations.filter((o) => o.requestId === first[0].requestId).length !== 1) {
      throw new ModelProofError(`Missing uniquely correlated first actual budget ${phase} probe`)
    }
    return first[0]
  }
  const first403 = probe('block', 403, timing.first403At)
  probe('raise', 200, timing.firstSuccessAt)
  if (timestamp(timing.blockSave.startedAt) > timestamp(timing.blockSave.savedAt) ||
      timestamp(timing.blockSave.savedAt) > timestamp(timing.first403At) ||
      timestamp(timing.first403At) > timestamp(timing.raiseSave.startedAt) ||
      timestamp(timing.raiseSave.startedAt) > timestamp(timing.raiseSave.savedAt) ||
      timestamp(timing.raiseSave.savedAt) > timestamp(timing.firstSuccessAt)) {
    throw new ModelProofError('Actual budget probes must follow their completed UI saves in block/raise order')
  }
  const key = createHash('sha256').update(scope.budget.grant.costCenterId).digest('hex').slice(0, 12)
  const timings: { gatewayId: string; tier: string; writeToFirst403Ms: number; writeToFirstSuccessMs: number }[] = []
  for (const gateway of scope.budget.managedGateways) {
    const snapshot = (phase: 'before' | 'block' | 'raise') => {
      const rows = evidence.namedValues?.filter((n) => n.gatewayId === gateway.id && n.phase === phase)
      if (rows?.length !== 1 || rows[0].source !== 'arm-get' || rows[0].secret !== false) throw new ModelProofError('Need independent plain ARM named-value snapshots on ALL managed gateways')
      timestamp(rows[0].observedAt)
      return rows[0]
    }
    const before = snapshot('before')
    const blocked = snapshot('block')
    const raised = snapshot('raise')
    const original = blockedKeys(before.value)
    if (original.includes(key) || JSON.stringify(blockedKeys(blocked.value)) !== JSON.stringify([...original, key].sort()) ||
        JSON.stringify(blockedKeys(raised.value)) !== JSON.stringify(original)) throw new ModelProofError('Only the isolated budget key may change; preserve other shared-list entries')
    if (timestamp(before.observedAt) > timestamp(runtime.timing.blockSave.startedAt) ||
        timestamp(blocked.observedAt) < timestamp(blocked.writeAuditAt) ||
        timestamp(blocked.observedAt) > timestamp(runtime.timing.raiseSave.startedAt) ||
        timestamp(raised.observedAt) < timestamp(raised.writeAuditAt)) throw new ModelProofError('Snapshots do not bracket this measured block/raise run')
    if (blocked.auditAction !== 'gateway.blockedCostCentersUpdated' || raised.auditAction !== 'gateway.blockedCostCentersUpdated') {
      throw new ModelProofError('Actual gateway write audits are required, not cached sync status')
    }
    const blockedAt = timestamp(blocked.writeAuditAt)
    const raisedAt = timestamp(raised.writeAuditAt)
    if (blockedAt < timestamp(runtime.timing.blockSave.startedAt) || blockedAt > timestamp(runtime.timing.raiseSave.startedAt) ||
        raisedAt < timestamp(runtime.timing.raiseSave.startedAt) ||
        (gateway.id === scope.gatewayId && (blockedAt > timestamp(runtime.timing.first403At) || raisedAt > timestamp(runtime.timing.firstSuccessAt)))) {
      throw new ModelProofError('Write audits do not precede measured runtime propagation')
    }
    // Only the fixture gateway was called. Other gateways prove list writes, NOT runtime latency.
    if (gateway.id === scope.gatewayId) timings.push({ gatewayId: gateway.id, tier: gateway.tier,
      writeToFirst403Ms: timestamp(runtime.timing.first403At) - blockedAt,
      writeToFirstSuccessMs: timestamp(runtime.timing.firstSuccessAt) - raisedAt })
  }
  denial(evidence, first403, 'budget')
  if (!runtime.observations.some((o) => o.case === 'budget-other-cost-center' && o.status === 200 && o.grant === scope.selection.other.id)) throw new ModelProofError('Other cost center was not independently allowed')
  return { timings, unavailableV2: !scope.budget.managedGateways.some((g) => g.tier === 'v2') }
}

export function governmentEmailEvidence(evidence: IndependentModelEvidence): void {
  const gov = evidence.government
  if (!gov || gov.cloud !== 'government' || !gov.resourceDeployed || !gov.domainDeployed || !gov.managedIdentity ||
      gov.tokenScope !== 'https://communication.azure.us/.default' || gov.apiVersion !== '2023-03-31') {
    throw new ModelProofError('R13 requires actual Azure Government deployment and ACS managed-identity evidence; commercial/source/mock evidence cannot pass')
  }
  if (gov.attempts.length !== 2 || !gov.attempts[0].operationId || gov.attempts[0].operationId !== gov.attempts[1].operationId ||
      gov.attempts[0].status !== 202 || ![200, 202, 409].includes(gov.attempts[1].status) ||
      timestamp(gov.attempts[1].at) < timestamp(gov.attempts[0].at)) throw new ModelProofError('Record two actual sends with the same Operation-Id and the observed second status')
  const observedThrough = observationWindow(gov.mailboxObservation, timestamp(gov.attempts[1].at))
  if (gov.receipts.length !== 1 || gov.receipts[0].operationId !== gov.attempts[0].operationId ||
      !gov.receipts[0].messageId || timestamp(gov.receipts[0].receivedAt) < timestamp(gov.attempts[0].at) ||
      timestamp(gov.receipts[0].receivedAt) > observedThrough) {
    throw new ModelProofError('ACS acceptance is not delivery; exactly one actual mailbox receipt is required')
  }
}

export interface NotificationDeliveryEvidence {
  amount: number
  /** Actual priced spend observed at successive checks, not synthetic input to a budget. */
  checks: { costCenterId: string; spend: number; through: string; observedAt: string }[]
  noticesBeforeRecheck: { costCenterId: string; id: string; kind: 'threshold' | 'blocked' | 'unblocked'; threshold?: number; status: string; operationId: string; sentAt: string }[]
  noticesAfterRecheck: string[]
  recheck: EvidenceWindow
  mailboxObservation: EvidenceWindow
  receipts: { operationId: string; messageId: string; receivedAt: string }[]
}

export function notificationDeliveryEvidence(scope: ModelJourneys, e: NotificationDeliveryEvidence): void {
  if (!scope.budget || cents(e.amount) !== cents(scope.budget.amount) ||
      e.checks.some((c) => c.costCenterId !== scope.budget!.grant.costCenterId) ||
      e.noticesBeforeRecheck.some((n) => n.costCenterId !== scope.budget!.grant.costCenterId)) {
    throw new ModelProofError('Notification checks/notices must identify the approved isolated cost center and budget amount')
  }
  if (cents(e.amount) < 1 || e.checks.length < 2) throw new ModelProofError('Need real staged budget checks')
  const reached = new Set<number>()
  const notified = new Map<number, number>()
  let through = -Infinity
  let checkedAt = -Infinity
  for (const check of e.checks) {
    const nextThrough = timestamp(check.through)
    const observedAt = timestamp(check.observedAt)
    if (nextThrough <= through || observedAt <= checkedAt || observedAt < nextThrough) {
      throw new ModelProofError('Notification checks must have independent advancing rollup evidence and ordered observation times')
    }
    through = nextThrough
    checkedAt = observedAt
    const next = [80, 100].filter((threshold) => cents(check.spend) >= cents(e.amount * threshold / 100) && !reached.has(threshold))
    next.forEach((threshold) => reached.add(threshold))
    if (next.length) notified.set(Math.max(...next), observedAt)
  }
  if (!reached.has(100)) throw new ModelProofError('Real priced checks never reached 100%')
  const notices = e.noticesBeforeRecheck
  const thresholds = notices.filter((n) => n.kind === 'threshold').map((n) => n.threshold).sort()
  if (notices.length !== notified.size + 2 ||
      JSON.stringify(thresholds) !== JSON.stringify([...notified.keys()].sort()) || notices.filter((n) => n.kind === 'blocked').length !== 1 ||
      notices.filter((n) => n.kind === 'unblocked').length !== 1 || notices.some((n) => n.status !== 'sent' || !n.operationId)) {
    throw new ModelProofError('Need only the highest threshold per check, and one actual sent block/unblock; skipped is not delivery')
  }
  if (notices.some((n) => !n.id) || new Set(notices.map((n) => n.id)).size !== notices.length ||
      new Set(notices.map((n) => n.operationId)).size !== notices.length ||
      JSON.stringify(notices.map((n) => n.id).sort()) !== JSON.stringify([...e.noticesAfterRecheck].sort())) throw new ModelProofError('Recheck changed notification identity/count; dedupe not proved')
  const blockedAt = timestamp(notices.find((n) => n.kind === 'blocked')!.sentAt)
  const raisedAt = timestamp(notices.find((n) => n.kind === 'unblocked')!.sentAt)
  if (blockedAt < notified.get(100)! || raisedAt < blockedAt) throw new ModelProofError('Block/unblock sends must follow the actual 100% check in order')
  const recheckedThrough = observationWindow(e.recheck, Math.max(checkedAt, ...notices.map((n) => timestamp(n.sentAt))))
  const observedThrough = observationWindow(e.mailboxObservation, recheckedThrough)
  if (e.receipts.length !== notices.length || new Set(e.receipts.map((r) => r.messageId)).size !== notices.length) throw new ModelProofError('Need exactly one independent mailbox message per notice')
  for (const notice of notices) {
    const sentAt = timestamp(notice.sentAt)
    if (notice.kind === 'threshold' && sentAt < notified.get(notice.threshold!)!) throw new ModelProofError('Threshold send predates its actual priced check')
    const receipts = e.receipts.filter((r) => r.operationId === notice.operationId)
    if (receipts.length !== 1 || !receipts[0].messageId) throw new ModelProofError('Duplicate or missing actual receipt')
    const receivedAt = timestamp(receipts[0].receivedAt)
    if (receivedAt < sentAt || receivedAt > observedThrough) throw new ModelProofError('Mailbox receipt must follow its notice send and precede the completed observation')
  }
}
