import type { BudgetOverview, BudgetView, EmailSettings } from '../types'

export const researchBudgetFixture: BudgetView = {
  id: 'budget_research',
  scope: 'costCenter',
  costCenter: { id: 'costCenter_research', name: 'Research', code: 'RES' },
  amount: 4000,
  currency: 'USD',
  thresholds: [80, 100],
  recipients: ['finance@contoso.com'],
  notifyOwners: true,
  owners: ['research-lead@contoso.com'],
  action: 'block',
  updatedAt: '2026-03-01T00:00:00Z',
  updatedBy: 'admin-oid',
  status: {
    level: 'blocked',
    month: '2026-03',
    monthToDate: 4320,
    forecast: 7440,
    used: 1.08,
    forecastUsed: 1.86,
    through: '2026-03-18T15:00:00Z',
    unpricedTokens: 0,
    crossed: [80, 100],
    blocked: true,
    blockedAt: '2026-03-18T15:05:00Z',
    unblockedAt: null,
    unblockReason: null,
    notifications: [
      {
        id: 'notice_80',
        kind: 'threshold',
        threshold: 80,
        reason: null,
        status: 'sent',
        recipients: 2,
        attempts: 1,
        createdAt: '2026-03-12T09:00:00Z',
        firstAttemptAt: '2026-03-12T09:00:00Z',
        sentAt: '2026-03-12T09:00:00Z',
        error: null,
      },
      {
        id: 'notice_blocked',
        kind: 'blocked',
        threshold: null,
        reason: 'budgetUsed',
        status: 'sent',
        recipients: 2,
        attempts: 1,
        createdAt: '2026-03-18T15:05:00Z',
        firstAttemptAt: '2026-03-18T15:05:00Z',
        sentAt: '2026-03-18T15:05:00Z',
        error: null,
      },
    ],
    evaluatedAt: '2026-03-18T15:05:00Z',
    error: null,
    gateways: [
      {
        gatewayId: 'gateway-prod',
        name: 'Production gateway',
        enforcing: true,
        syncedAt: '2026-03-18T15:05:00Z',
        error: null,
      },
    ],
  },
}

export const supportBudgetFixture: BudgetView = {
  ...researchBudgetFixture,
  id: 'budget_support',
  costCenter: { id: 'costCenter_support', name: 'Customer Support', code: 'CS-110' },
  amount: 10000,
  action: 'continue',
  recipients: [],
  status: {
    ...researchBudgetFixture.status,
    level: 'warning',
    monthToDate: 8800,
    forecast: 15100,
    used: 0.88,
    forecastUsed: 1.51,
    crossed: [80],
    blocked: false,
    blockedAt: null,
    notifications: [researchBudgetFixture.status.notifications[0]],
    gateways: [],
  },
}

export const organizationBudgetFixture: BudgetView = {
  ...researchBudgetFixture,
  id: 'budget_organization',
  scope: 'organization',
  costCenter: null,
  amount: 50000,
  action: 'continue',
  notifyOwners: false,
  owners: [],
  recipients: ['cfo@contoso.com'],
  status: {
    ...researchBudgetFixture.status,
    level: 'ok',
    monthToDate: 13120,
    forecast: 22600,
    used: 0.2624,
    forecastUsed: 0.452,
    crossed: [],
    blocked: false,
    blockedAt: null,
    notifications: [],
    gateways: [],
  },
}

export const budgetOverviewFixture: BudgetOverview = {
  month: '2026-03',
  organization: organizationBudgetFixture,
  costCenters: [researchBudgetFixture, supportBudgetFixture],
  unbudgeted: 2,
  email: { enabled: true, ready: true },
  priced: true,
  notes: [],
}

export const emptyBudgetOverviewFixture: BudgetOverview = {
  month: '2026-03',
  organization: null,
  costCenters: [],
  unbudgeted: 4,
  email: { enabled: false, ready: false },
  priced: true,
  notes: [],
}

export const emailSettingsFixture: EmailSettings = {
  enabled: false,
  endpoint: null,
  sender: null,
  ready: false,
  updatedAt: null,
  updatedBy: null,
  lastTestAt: null,
  lastTestError: null,
  suggestedEndpoint: 'https://contoso-mosaic.communication.azure.com',
  suggestedSender: 'DoNotReply@contoso.azurecomm.net',
}
