import type {
  Entitlement,
  ModelAccessSnapshot,
  ModelApi,
  ModelConnection,
  Publication,
  PublishPlan,
} from '../types'

const timestamp = '2026-09-01T12:00:00Z'

export const accessSnapshot: ModelAccessSnapshot = {
  version: 1,
  settings: { keysEnabled: true, entraEnabled: true },
  audience: 'api://model-runtime',
  publicationEnforcement: {
    counterKeyExpression: 'publication-counter',
    tokensPerMinute: 12000,
    estimatePromptTokens: true,
  },
  grants: [{
    entitlementId: 'direct_grant',
    subject: { kind: 'user', id: 'principal_1' },
    objectId: 'user-object-1',
    displayName: 'Ada Lovelace',
    subscriptionName: 'dedicated-user-sub',
    enabled: true,
    enforcement: null,
    intentDigest: 'grant-digest',
  }],
}

export const modelPublication: Publication = {
  id: 'pub_1',
  tenantId: 'tenant',
  entityType: 'publication',
  gatewayId: 'gateway_1',
  modelEndpointId: 'endpoint_1',
  deploymentName: 'gpt-4o',
  provider: 'azureOpenAi',
  displayName: 'Published chat',
  apiName: 'chat',
  apiPath: 'models/chat',
  backendName: 'backend',
  fragmentName: 'fragment',
  productName: 'product',
  subscriptionName: 'legacy-bootstrap',
  subscriptionRequired: false,
  enforcement: accessSnapshot.publicationEnforcement,
  shapeVersion: '1',
  status: 'published',
  resources: [],
  lastPlanId: 'plan_1',
  lastPlanDigest: 'digest',
  lastRunId: 'run_1',
  lastAppliedAt: timestamp,
  lastError: null,
  modelApiId: 'modelApi_1',
  governedAccess: accessSnapshot.settings,
  appliedAccess: accessSnapshot,
  accessState: 'applied',
  createdAt: timestamp,
  updatedAt: timestamp,
}

export const publishedModelApi: ModelApi = {
  id: 'modelApi_1',
  tenantId: 'tenant',
  gatewayId: 'gateway_1',
  publicationId: modelPublication.id,
  apiName: 'chat',
  displayName: 'Chat completions',
  path: 'models/chat',
  protocols: ['https'],
  aiKind: 'azureOpenAi',
  aiSignals: [],
  subscriptionRequired: false,
  operationCount: 1,
  productNames: [],
  visibility: 'catalog',
  selection: 'manual',
  importedFromSnapshotId: null,
  importedAt: timestamp,
  createdAt: timestamp,
  updatedAt: timestamp,
}

export const directGrant: Entitlement = {
  id: 'direct_grant',
  tenantId: 'tenant',
  subject: accessSnapshot.grants[0].subject,
  resource: { kind: 'modelApi', id: publishedModelApi.id },
  enabled: true,
  enforcement: null,
  binding: {
    gatewayId: 'gateway_1',
    source: 'orchestrated',
    apimSubscriptionName: 'dedicated-user-sub',
  },
  runtime: {
    publicationId: modelPublication.id,
    status: 'applied',
    appliedMethods: accessSnapshot.settings,
    subscriptionName: 'dedicated-user-sub',
    appliedAt: timestamp,
  },
  createdAt: timestamp,
  updatedAt: timestamp,
}

export const connectionInfo: ModelConnection = {
  entitlementId: directGrant.id,
  publicationId: modelPublication.id,
  gatewayId: modelPublication.gatewayId,
  endpoint: 'https://gateway.example.test/models/chat',
  deploymentName: modelPublication.deploymentName,
  tenantId: 'tenant',
  runtime: directGrant.runtime,
  appliedMethods: accessSnapshot.settings,
  entraAudience: accessSnapshot.audience,
  entraScope: 'api://model-runtime/Models.Invoke',
  subscriptionHeader: 'Ocp-Apim-Subscription-Key',
  operations: [{ name: 'chat', method: 'POST', path: '/chat/completions' }],
  publicationLimits: accessSnapshot.publicationEnforcement,
  grantLimits: null,
}

export const accessPlan: PublishPlan = {
  id: 'access-plan',
  tenantId: 'tenant',
  entityType: 'publishPlan',
  publicationId: modelPublication.id,
  gatewayId: modelPublication.gatewayId,
  digest: 'access-digest',
  steps: [],
  facets: [],
  policyContentSha256: 'policy-digest',
  warnings: [],
  accessSnapshot,
  previousAccessVersion: null,
  createdAt: timestamp,
  updatedAt: timestamp,
}
